### ISSUE TITLE
Always getting "Required child 'trak' is missing from string metadata atom with identifier 'moov'"

### ISSUE THREAD

**Issue by theolecoutre** [NCrusher74/SwiftTaggerMP4#12]
Hello,

No matter the mp4 video file I use as an input I always get this error when trying :

let mp4Url = URL(fileURLWithPath: "/Users/theo/Downloads/test.mp4")
let mp4File = try Mp4File(location: mp4Url)

Has someone an idea to solve it ?

Thanks.

**Comment by NCrusher74** [comment]
Hi, as it says at the top of the README: "SwiftTaggerMp4 is a Swift library for reading and writing metadata and chapter tags in MP4 **AUDIO** files."

There's no support for video files built in, and if the videos you're using don't have an audio track `trak` atom, that is the error you will get.

And honestly, since the library is for managing metadata, there's not a lot of support for audio handling in there either. Just enough to make sure what we're working with is an audio track.

I just don't understand enough about audio or video processing to feel secure implementing that functionality myself. So anything that isn't actually involved in metadata tagging just gets passed through.

While I didn't implement most of the audio and video atoms, though I did sort of sketch a lot of them out. They're located in `
SwiftTaggerMP4/Sources/SwiftTaggerMP4/Atoms/ParsingStructures/unhandled/` and if you want to take a crack at implementing  that functionality yourself, I will be happy to entertain a pull request.
